docs_dir: docs

repo_url: https://github.com/openfoodfacts/brand-images
edit_uri: blob/main/docs/

site_name: Brand Images
site_dir: site

theme:
  name: material
  custom_dir: docs/overrides
  logo: https://static.openfoodfacts.org/images/logos/off-logo-horizontal-light.svg
  favicon: https://static.openfoodfacts.org/images/logos/off-logo-favicon-light.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: README.md
  - Open Prices:
    - Brand Match Viewer: open-prices/brand-match-viewer.md
    - Brand Match Stats: open-prices/brand-match-stats.md
  - NSI:
    - Brand Match Viewer: nsi/brand-match-viewer.md
    - Brand Match Stats: nsi/brand-match-stats.md
  - Dev:
    - Contributing: CONTRIBUTING.md

plugins:
  - search

extra:
  brand_match_logo_base: !ENV [BRAND_MATCH_LOGO_BASE, ../../xx/stores/]
