"""
Update the README Content section with per-folder stats from xx/.

Usage:
    python3 scripts/update_readme_xx_stats.py
"""

from __future__ import annotations

import datetime
from pathlib import Path

README_HEADING = "## Content"
MARKER_START = "<!-- Auto-generated by scripts/update_readme_xx_stats.py START -->"
MARKER_END = "<!-- Auto-generated by scripts/update_readme_xx_stats.py END -->"


def count_files(folder: Path) -> int:
    return sum(1 for path in folder.rglob("*") if path.is_file())


def count_unique_files(folder: Path) -> int:
    unique_keys = {
        path.relative_to(folder).with_suffix("").as_posix()
        for path in folder.rglob("*")
        if path.is_file()
    }
    return len(unique_keys)


def count_files_by_extension(folder: Path) -> tuple[int, int]:
    svg_count = 0
    png_count = 0
    for path in folder.rglob("*"):
        if not path.is_file():
            continue
        suffix = path.suffix.lower()
        if suffix == ".svg":
            svg_count += 1
        elif suffix == ".png":
            png_count += 1
    return svg_count, png_count


def read_descriptions(readme_path: Path) -> dict[str, str]:
    """Parse folder->description from the existing Content table in README."""
    descriptions: dict[str, str] = {}
    lines = readme_path.read_text(encoding="utf-8").splitlines()
    in_section = False
    in_generated = False
    for line in lines:
        if line.strip() == README_HEADING:
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if line.strip() == MARKER_START:
            in_generated = True
            continue
        if line.strip() == MARKER_END:
            in_generated = False
            continue
        if in_section and not in_generated and line.startswith("|"):
            cells = [c.strip() for c in line.strip().split("|")[1:-1]]
            if len(cells) >= 2 and cells[0].startswith("`xx/"):
                folder_name = cells[0].strip("`").split("/", 1)[1]
                descriptions[folder_name] = cells[1]
    return descriptions


def build_table(xx_dir: Path, readme_path: Path) -> str:
    descriptions = read_descriptions(readme_path)
    subdirs = sorted(path for path in xx_dir.iterdir() if path.is_dir())
    rows = []
    for subdir in subdirs:
        total_count = count_files(subdir)
        unique_count = count_unique_files(subdir)
        svg_count, png_count = count_files_by_extension(subdir)
        desc = descriptions.get(subdir.name, "")
        rows.append((subdir.name, desc, total_count, unique_count, svg_count, png_count))

    lines = [
        "| Folder | Description | Items (Unique) | SVG | PNG |",
        "|--------|-------------|----------------:|----:|----:|",
    ]
    for name, desc, count, unique_count, svg_count, png_count in rows:
        folder_path = f"xx/{name}"
        lines.append(f"| `{folder_path}` | {desc} | {count} ({unique_count}) | {svg_count} | {png_count} |")
    return "\n".join(lines)


def build_last_updated_line() -> str:
    today = datetime.date.today().strftime("%Y-%m-%d")
    return f"Last updated: {today}"


def find_section_bounds(lines: list[str], heading: str) -> tuple[int, int]:
    start = next((idx for idx, line in enumerate(lines) if line.strip() == heading), -1)
    if start == -1:
        raise RuntimeError(f"Could not find heading: {heading}")

    end = len(lines)
    for idx in range(start + 1, len(lines)):
        if lines[idx].startswith("## "):
            end = idx
            break

    return start, end


def update_readme(readme_path: Path, table: str, last_updated_line: str) -> None:
    lines = readme_path.read_text(encoding="utf-8").splitlines()
    start, end = find_section_bounds(lines, README_HEADING)

    new_section = [
        lines[start],
        "",
        MARKER_START,
        table,
        "",
        last_updated_line,
        MARKER_END,
        "",
    ]

    updated = lines[:start] + new_section + lines[end:]
    readme_path.write_text("\n".join(updated).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    readme_path = repo_root / "README.md"
    xx_dir = repo_root / "xx"

    if not xx_dir.exists() or not xx_dir.is_dir():
        raise RuntimeError(f"Missing xx directory: {xx_dir}")

    table = build_table(xx_dir, readme_path)
    last_updated_line = build_last_updated_line()
    update_readme(readme_path, table, last_updated_line)
    print(f"Updated {readme_path}")


if __name__ == "__main__":
    main()
