"""
Update the README stats section with per-folder counts from xx/.

Usage:
    python3 scripts/update_readme_xx_stats.py
"""

from __future__ import annotations

import datetime
from pathlib import Path

README_HEADING = "## Stats"


def count_files(folder: Path) -> int:
    return sum(1 for path in folder.rglob("*") if path.is_file())


def count_unique_files(folder: Path) -> int:
    unique_keys = {
        path.relative_to(folder).with_suffix("").as_posix()
        for path in folder.rglob("*")
        if path.is_file()
    }
    return len(unique_keys)


def count_files_by_extension(folder: Path) -> tuple[int, int]:
    svg_count = 0
    png_count = 0
    for path in folder.rglob("*"):
        if not path.is_file():
            continue
        suffix = path.suffix.lower()
        if suffix == ".svg":
            svg_count += 1
        elif suffix == ".png":
            png_count += 1
    return svg_count, png_count


def build_table(xx_dir: Path) -> str:
    subdirs = sorted(path for path in xx_dir.iterdir() if path.is_dir())
    rows = []
    for subdir in subdirs:
        total_count = count_files(subdir)
        unique_count = count_unique_files(subdir)
        svg_count, png_count = count_files_by_extension(subdir)
        rows.append((subdir.name, total_count, unique_count, svg_count, png_count))

    lines = [
        "| Folder | Items (Unique) | SVG | PNG |",
        "|--------|----------------:|----:|----:|",
    ]
    for name, count, unique_count, svg_count, png_count in rows:
        folder_path = f"xx/{name}"
        lines.append(f"| `{folder_path}` | {count} ({unique_count}) | {svg_count} | {png_count} |")
    return "\n".join(lines)


def build_last_updated_line() -> str:
    today = datetime.date.today().strftime("%Y-%m-%d")
    return f"Last updated: {today}"


def find_section_bounds(lines: list[str], heading: str) -> tuple[int, int]:
    start = next((idx for idx, line in enumerate(lines) if line.strip() == heading), -1)
    if start == -1:
        raise RuntimeError(f"Could not find heading: {heading}")

    end = len(lines)
    for idx in range(start + 1, len(lines)):
        if lines[idx].startswith("## "):
            end = idx
            break

    return start, end


def update_readme(readme_path: Path, table: str, last_updated_line: str) -> None:
    lines = readme_path.read_text(encoding="utf-8").splitlines()
    start, end = find_section_bounds(lines, README_HEADING)

    new_section = [
        lines[start],
        "",
        "<!-- Auto-generated by scripts/update_readme_xx_stats.py START -->",
        table,
        "",
        last_updated_line,
        "<!-- Auto-generated by scripts/update_readme_xx_stats.py END -->",
        "",
    ]

    updated = lines[:start] + new_section + lines[end:]
    readme_path.write_text("\n".join(updated).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    readme_path = repo_root / "README.md"
    xx_dir = repo_root / "xx"

    if not xx_dir.exists() or not xx_dir.is_dir():
        raise RuntimeError(f"Missing xx directory: {xx_dir}")

    table = build_table(xx_dir)
    last_updated_line = build_last_updated_line()
    update_readme(readme_path, table, last_updated_line)
    print(f"Updated {readme_path}")


if __name__ == "__main__":
    main()
